#!/bin/sh

if [ ! "$#" = 1 ]
then for i in deque flex-vector plist env exp parse; do $0 $i; done
else
    scm -l "wrapper.ss" -c "(unit-test-$1)"
    # mzscheme -f "wrapper.ss" -e "(unit-test-$1)"
fi
